version: '3.2'

services:
  postgres:
    restart: always
    image: postgres:12.2
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=network_inventory
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /var/lib/postgresql:/var/lib/postgresql
